# --- GhostSMTP OpenDMARC Configuration ---

# Identification of authorization authentication results headers
AuthservID              mail.ghostsmtp.com

# Listen on TCP port 54321 for Postfix connections
Socket                  inet:54321@0.0.0.0

# User configuration
UserID                  opendmarc
PidFile                 /var/run/opendmarc/opendmarc.pid

# Logging settings
Syslog                  yes

# Policies verification parameters
RejectFailures          false
TrustedAuthservIDs      mail.ghostsmtp.com

# Ignore localhost requests (requires file path if enabled)
# IgnoreHosts             127.0.0.1, localhost
