# --- GhostSMTP Dovecot Configuration ---

# Protocols enabled
protocols = imap lmtp

# Log settings
log_path = /dev/stdout
info_log_path = /dev/stdout
debug_log_path = /dev/stdout

# Mail location and storage structures
mail_location = maildir:/var/mail/%d/%n:LAYOUT=fs
mail_uid = vmail
mail_gid = vmail

first_valid_uid = 1000
last_valid_uid = 1000

# SSL Configurations (Placeholder SSL)
ssl = yes
ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key

service lmtp {
  inet_listener lmtp {
    port = 24
  }
}

service auth {
  inet_listener auth-postfix {
    port = 10001
  }
}

auth_mechanisms = plain login

passdb {
  driver = checkpassword
  args = /etc/dovecot/auth-helper.sh
}

userdb {
  driver = static
  args = uid=1000 gid=1000 home=/var/mail/%d/%n
}
